[package]
name = "kafka-protocol"
version = "0.1.0"
authors = ["Sonny Scroggin <sonny@scrogg.in>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
futures-preview = { version = "0.3.0-alpha" }
num_enum = "0.4"

[dev-dependencies]
async-std = "0.99"
